package uz.mobile.joybox.presentation.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF6BF1F6)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDEE0FF)
val onPrimaryContainerLight = Color(0xFF0C154B)
val secondaryLight = Color(0xFF5B5D72)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE0E1F9)
val onSecondaryContainerLight = Color(0xFF181A2C)
val tertiaryLight = Color(0xFF77536D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD7F1)
val onTertiaryContainerLight = Color(0xFF2D1227)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFF0F1111)
val onBackgroundLight = Color(0xFF1B1B21)
val surfaceLight = Color(0xFFFBF8FF)
val onSurfaceLight = Color(0xFF1B1B21)
val surfaceVariantLight = Color(0xFFE3E1EC)
val onSurfaceVariantLight = Color(0xFF46464F)
val outlineLight = Color(0xFF767680)
val outlineVariantLight = Color(0xFFC7C5D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303036)
val inverseOnSurfaceLight = Color(0xFFF2EFF7)
val inversePrimaryLight = Color(0xFFBBC3FF)
val surfaceDimLight = Color(0xFFDBD9E0)
val surfaceBrightLight = Color(0xFFFBF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF5F2FA)
val surfaceContainerLight = Color(0xFFEFEDF4)
val surfaceContainerHighLight = Color(0xFFE9E7EF)
val surfaceContainerHighestLight = Color(0xFFE4E1E9)

val secondaryTextColorDark = Color(0xFFB9BFC1)
val darkGreyTextColorDark = Color(0xFF5D6B6B)
val hintTextColorDark = Color(0xFF747E83)
val videoSeekbarInactiveColor = Color(0xFF1E1E1E)
val appBarTextColor = Color(0xFFFFFFFF)
val headlineMediumTextColorDark = Color(0xFFEEEFF0)
val bodyLargeTextColorDark = Color(0xFFB9BFC1)
val mainButtonTextColorDark = Color(0xFF191B1C)
val bottomSheetBackgroundColor = Color(0x191B1C99)
val secondaryButtonTextColorDark = Color(0xFFEEEFF0)
val textButtonTextColorDark = Color(0xFFD0D0D0)
val progressBarBackgroundColor = Color(0x40FFFFFF)
val textFieldBorderColorDark = Color(0xFF656E72)
val headlineMediumTextColorLight = Color(0xFFEEEFF0)
val bodyLargeTextColorLight = Color(0xFFB9BFC1)
val mainButtonTextColorLight = Color(0xFF191B1C)
val secondaryButtonTextColorLight = Color(0xFFEEEFF0)
val disableButtonColor = Color(0xFF272B2C)
val textGrey60ColorDark = Color(0xFF6A6E7F)
val timerBorderColor = Color(0xFFCDCFD4)
val darkGreyBodyTextColor = Color(0xFFBDC1C6)
val commentCardBackgroundColor = Color(0xFF272B30)
val commentTextColor = Color(0xFFE9EAEA)
val reviewStarColor  = Color(0xFFF3B22C)
val commentFieldBackgroundColor  = Color(0xFF222423)
val balanceErrorBackgroundColor  = Color(0xFF202123)
val deleteTextColor  = Color(0xFFE72006)
val cancelButtonBorderColor  = Color(0xFF5F5F5F)

val primaryDark = Color(0xFF6BF1F6)
val onPrimaryDark = Color(0xFF232C61)
val primaryContainerDark = Color(0xFF3A4379)
val onPrimaryContainerDark = Color(0xFFDEE0FF)
val secondaryDark = Color(0xFFC4C5DD)
val onSecondaryDark = Color(0xFF2D2F42)
val secondaryContainerDark = Color(0xFF434559)
val onSecondaryContainerDark = Color(0xFFE0E1F9)
val tertiaryDark = Color(0xFFE6BAD7)
val onTertiaryDark = Color(0xFF44263D)
val tertiaryContainerDark = Color(0xFF5D3C54)
val onTertiaryContainerDark = Color(0xFFFFD7F1)
val errorDark = Color(0xFFAD1F1F)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1111)
val onBackgroundDark = Color(0xFFE4E1E9)
val surfaceDark = Color(0xFF131318)
val onSurfaceDark = Color(0xFFE4E1E9)
val surfaceVariantDark = Color(0xFF46464F)
val onSurfaceVariantDark = Color(0xFFC7C5D0)
val outlineDark = Color(0xFF90909A)
val outlineVariantDark = Color(0xFF46464F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE4E1E9)
val inverseOnSurfaceDark = Color(0xFF303036)
val inversePrimaryDark = Color(0xFF525A92)
val surfaceDimDark = Color(0xFF131318)
val surfaceBrightDark = Color(0xFF39393F)
val surfaceContainerLowestDark = Color(0xFF0D0E13)
val surfaceContainerLowDark = Color(0xFF1B1B21)
val surfaceContainerDark = Color(0xFF1F1F25)
val surfaceContainerHighDark = Color(0xFF29292F)
val surfaceContainerHighestDark = Color(0xFF34343A)






